global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.

# rule_files:
#   - "rules/node.rules"

scrape_configs:
  # - job_name: 'prometheus'
  #   scrape_interval: 5s
  #   static_configs:
  #     - targets: ['localhost:9090']

  - job_name: 'node'
    scrape_interval: 8s
    static_configs:
      - targets: ['192.168.1.5:9100', '192.168.1.101:9100']

  - job_name: 'kong'
    scrape_interval: 8s
    static_configs:
      - targets: ['192.168.1.5:8999']



      