FROM ubuntu:16.04 
MAINTAINER zw "zw@spwx.me" 
RUN apt-get update \
  && apt-get install -y python3-pip python3-dev libmysqlclient-dev\
  && cd /usr/local/bin \
  && ln -s /usr/bin/python3 python \
  && pip3 install --upgrade pip \
  && apt-get remove \
  && apt-get clean
  
